name: run tests

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        node-version:
          - 16.15.x
        platform:
          - ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node env
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: npm install
        run: npm install

      - name: Setup .env
        run: cp $PWD/.env.sample $PWD/.env

      - name: run tests w coverage
        run: npm run test:coverage

      - name: Upload test coverage
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
