name: run tests

on: [pull_request]

jobs:
  test:

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        node-version:
          - 16.15.x
        platform:
          - ubuntu-latest

    services:
      mongo:
        image: mongodb:latest
        ports:
          - 27017:27017

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node env
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Verify Redis connection
        env:
          PORT: ${{ job.services.redis.ports[6379] }}
        run: |
          while ! redis-cli ping | grep PONG; do
          sleep 1
          done

      - name: Verify Mongo connection
        run: |
          until nc -z localhost 27017
          do
            sleep 1
          done

      - name: npm install
        run: npm install

      - name: npm test
        run: npm test
